name: Feature Subtarea (st)
description: Agregar subtarea que pertenece a una tarea padre que agrega una nueva funcionalidad
labels: [subtarea]

body:
  - type: input
    id: parent
    attributes:
      label: Tarea padre
      description: 'Numero de la tarea padre a la que pertenece esta subtarea, Ejemplo: "- #12345"'
      placeholder: "- #numero_de_tarea_padre"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción de la tarea que se ha realizado
      description: Explica detalladamente
      value: Aqui explica detalladamente lo que se hizo...
    validations:
      required: false
