name: POC
description: Realizar una prueba de concepto de alguna libreria o tecnologia, etc.
labels: [poc, doc]

body:
  - type: input
    id: descripcion
    attributes:
      label: Descripción del problema
      value: Aqui explica detalladamente...
    validations:
      required: false

  - type: input
    id: solucion
    attributes:
      label: Descripción de como se solucionó
      value: Aqui explica detalladamente...
    validations:
      required: false

  - type: checkboxes
    id: subtareas
    attributes:
      label: Sub tareas
      description: La secuencia de tareas que se van a realizar
      options:
        - label: Investigación y lectura de la documentación
        - label: Creación del POC
        - label: Documentación en discussions

  - type: textarea
    id: documentacion
    attributes:
      label: Enlaces de documentación y/o libros que se usaron
      description: Aqui debes colocar todos los enlaces usando markdown
      value: |
        - [Ejemplo 1](https://example.com)
        - [Ejemplo 2](https://example.com)
    validations:
      required: false
