import type { Metadata } from 'next';
import '@/styles/index.css';
import Header from '@/components/Header';
import { ThemeProvider } from '@mui/material';
import { themeApp } from '@/theme/themeApp';

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'VIGUI',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang='es'>
      <body>
        <ThemeProvider theme={themeApp}>
          <Header />
          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
