import { Box } from '@mui/material';
import type { Metadata } from 'next';

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'VIGUI - Admin',
  description: 'Generated by create next app',
};

const AdminLayout = ({ children }: Props) => {
  return <Box component='main'>{children}</Box>;
};

export default AdminLayout;
