import type { Metadata } from 'next';

type Props = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: 'VIGUI - Admin',
  description: 'Generated by create next app',
};

const AdminLayout = ({ children }: Props) => {
  return <div>{children}</div>;
};

export default AdminLayout;
